# Generated by Django 3.2.19 on 2023-07-08 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_auto_20230606_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='updatedAt',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 8, 13, 9, 50, 126344)),
        ),
    ]
