# Generated by Django 3.2.19 on 2023-07-08 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0010_alter_device_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='updatedAt',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 7, 8, 13, 12, 30, 402735)),
        ),
    ]
